### ISSUE TITLE
osx how to run from command line

### ISSUE THREAD

**Issue by jabad3hut** [jonashaag/bjoern#109]
Using the documentation as reference:

        # Bind to TCP host/port pair:
	bjoern.run(wsgi_application, host, port)

	 # TCP host/port pair, enabling SO_REUSEPORT if available.
	bjoern.run(wsgi_application, host, port, reuse_port=True)

	 # Bind to Unix socket:
	bjoern.run(wsgi_application, 'unix:/path/to/socket')

	 # Bind to abstract Unix socket: (Linux only)
	bjoern.run(wsgi_application, 'unix:@socket_name')

is assuming that you are in a python cmd line session and have imported bjoern.  This seems cumbersome.
I believe there is also an assumption that the wsgi_application has also been imported.  Is this true?  Also, how would you actually run this in a production, non-terminal, non-python session environment?

**Comment by jonashaag** [comment]
Save the above code in a Python script and run it?

**Comment by jonashaag** [comment]
Save the above code in a Python script and run it?

**Comment by marchon** [comment]
jabad3hut were you satisfied with that explanation? 

1. You will need a launch script
2. a virtual environment (to keep all of your packages and dependencies self-contained and not conflicting with system packages) 
1. A couple of command line actions to make the script executable. 

start with making a directory and putting this file in it. 

simple_flask_app.py 

```python
#!./env/bin/python

from flask import render_template, redirect, url_for, request, session, flash, Response, Flask 
import bjoern 

app = Flask(__name__)
app.config["DEBUG"] = True

@app.route("/", methods=["GET", "POST"])
def hello_world():
    """ serve root directory request with a static message and output to the log """
    
    print "This line will be output to the console log"

    # Send the response.
    resp = 'These are not the doids you are looking for... You may go. '
    return str(resp)

if __name__ == "__main__":
    # if You want to use Flask's internal method to run the wsgi script you would use app.run
    # app.run(host = '0.0.0.0', port = 5000)
    # instead you want this line below  
    bjoern.run(app, '0.0.0.0', 5000, reuse_port=True)

```

Second, Install a virtual environment 
(I would recommend that you run it in a directory with a virtual environment.) 
I like to use the commands 

```bash
virtualenv env 

source env/bin/activate

pip install flask 
pip install bjoern

chmod +x simple_flask_app.py

```

and now the app can be launched from that directory as 

./simple_flask__app.py  (it knows where to find python and dependencies / flask, bjoern etc.) 


Whenever you want to go in and work on adding packages or making changes, simply go to that directory - activate the virtualenvironment again, install what you need and make changes as you see fit. 

to activate the virtualenv use the bash command below.

# source env/bin/activate 

after you add packages and such - I would save a list of my installed packages with versions into a requirements.txt with the following command.

```bash 
pip freeze > requirements.txt 
```

This requirements.txt file can be loaded into another virtualenv anytime you want to with 

```
pip install -r requirements.txt 
```
 If these instructions were unclear - please let me know so that I can fix them for others, and I hope that it helps.  If you need a little more information - send me a message or reply here, and have a great day!

**Comment by frankh** [comment]
As an alternative to writing a script, you can just do it in a single command:

`python -c "from myapp.wsgi import application; import bjoern; bjoern.run(application, '0.0.0.0', 8000)"`
