### ISSUE TITLE
GitHub wiki is outdated

### ISSUE THREAD

**Issue by maxifom** [jonashaag/bjoern#207]
Github wiki contains installation for python2 which is deprecated right now, I think it would be nice to rewrite it to the current situation, or just remove link from README to not confuse people

**Comment by jonashaag** [comment]
Anyone feel free to take a stab at the changes.

**Comment by JonasR** [comment]
I updated it in-place. Hopefully that's what you meant as there is (to my knowledge) no PR workflow for wikis.

Checked my edits with the latest versions of Ubuntu/Fedora/Arch in Docker. Mac OS is my best guess as I don't have anything to test with. I also left the python2 stuff in as an alternative for now.

Further added a note that Windows is not supported (as denoted in #119) since that wasn't immediately clear to me either :)

**Comment by jonashaag** [comment]
Wow, awesome, thank you <3
