### ISSUE TITLE
Why is wsgi.multithread set to True?

### ISSUE THREAD

**Issue by Cito** [jonashaag/bjoern#96]
The homepage says Bjoern is single-threaded, yet the env variable `wsgi.multithread` is set to `True` in `request.c`. Shouldn't it be set to `False`?

As far as I understand, the server is telling the application which capabilities it has resp. makes use of, so the application can take that into consideration. For instance, it might enhance performance by not locking access of global variables that might be used e.g. as per-process caches if  it knows that the server is single-threaded anyway.

**Comment by jonashaag** [comment]
Hm, I not even sure I understand the WSGI spec at this point.


<dl><dt>wsgi.multithread</dt><dd>This value should evaluate true if the application object may be simultaneously invoked by another thread in the same process, and should evaluate false otherwise.</dd><dt>wsgi.multiprocess</dt><dd>This value should evaluate true if an equivalent application object may be simultaneously invoked by another process, and should evaluate false otherwise.</dd></dl>

These refer to the application, so do they even have to be set by the WSGI server at all? Not sure.

**Comment by Cito** [comment]
Yes, the specs do not explain the purpose of the flag very well. As far as I understand, it is a hint from the server to the application. See [Processes and Threading](http://modwsgi.readthedocs.io/en/develop/user-guides/processes-and-threading.html) in the mod_wsgi docs for a good explanation. All the other WSGI servers implement this similarly. For instance, [Waitress](http://docs.pylonsproject.org/projects/waitress/en/latest/) which is multi-threaded, but single-process sets `wsgi.multithread=True` and `wsgi.multiprocess=False`. Since Bjoern is single-threaded, but multi-process, it should set these flags the other way around.

**Comment by jonashaag** [comment]
Thanks for the explanation. I agree with your point. Pull request welcome! :-)

**Comment by jaap3** [comment]
This issue is resolved and can be closed, correct?

**Comment by jonashaag** [comment]
No
